env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash
    TOKEN: ENCRYPTED[6d518771e557b56baebb2ede3d91059daa8f1b7750843a0875a5cfc9613595b78879dfafd75d4f058ae3b9927878e1d5]
    BOT_TOKEN: ENCRYPTED[!56696dbfb5e7fcd2790dd9ceb333b5c9d0bda790c643b097d271bf6d603a84a12feebb8f0ae4c2cd9599abe59405441f!]

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      # image: ghcr.io/sushrut1101/docker:arch
      image: ubuntu:latest
      cpu: 8
      memory: 20G

  Checks_script:
      - apt-get -y update
      - apt-get -y upgrade
      - apt-get -y install curl
      - apt-get -y install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex bison aria2 jq
      - curl -sL https://raw.githubusercontent.com/Hakimi0804/OrangeFox-CI/main/pbrp-build.sh | bash
