env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      # image: ghcr.io/sushrut1101/docker:arch
      image: ubuntu:latest
      cpu: 8
      memory: 20G

  Checks_script:
      - apt-get -y update
      - apt-get -y upgrade
      - apt-get -y install curl
      - apt-get -y install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex bison aria2 jq
      - curl -sL https://raw.githubusercontent.com/dumpydev/OrangeFox-CI/main/pbrp-build.sh | bash
